---
label: Services
hide_body: true
fields:
- name: service_title
  type: text
  config:
    required: false
  label: Title
- name: service_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: service_photo
  type: file
  config:
    maxSize: 64
  label: Photo
- name: service_image_alt
  type: text
  config:
    required: false
  label: Image Alt
- name: service_button
  type: field_group
  config: {}
  fields:
  - name: service_button_label
    type: text
    config:
      required: false
    label: Button Label
  label: Button
pages:
- content/services/testing-new-services.md
